#pragma once
// =============================================================================
// VMM Shadow Mapper - Embedded Payload Binaries
// Generated by generate_payload_header.ps1
// DO NOT EDIT MANUALLY - Regenerate from source .sys files
// =============================================================================

#include <cstddef>
#include <cstdint>

namespace payload {

// rwbase payload - Size: 13824 bytes
extern const unsigned char rwbase_image[];
extern const size_t rwbase_image_size;

} // namespace payload
