param(
    [string]$DkomPath = "d:\RWbase\RWbase\DKOM.sys",
    [string]$RwbasePath = "d:\RWbase\RWbase\RWbase.sys",
    [string]$OutputPath = "d:\Hyper\shared\payload\payload_bin.h"
)

function Convert-BinaryToCArray {
    param([string]$FilePath, [string]$VarName)
    
    if (-not (Test-Path $FilePath)) {
        Write-Error "File not found: $FilePath"
        return $null
    }
    
    $bytes = [System.IO.File]::ReadAllBytes($FilePath)
    $hexLines = @()
    
    for ($i = 0; $i -lt $bytes.Length; $i += 16) {
        $end = [math]::Min($i + 15, $bytes.Length - 1)
        $lineBytes = $bytes[$i..$end]
        $hexValues = $lineBytes | ForEach-Object { "0x{0:X2}" -f $_ }
        $hexLines += "    " + ($hexValues -join ", ")
    }
    
    $arrayContent = $hexLines -join ",`n"
    
    return @"

// $VarName payload - Size: $($bytes.Length) bytes
const unsigned char ${VarName}_image[] = {
$arrayContent
};
const size_t ${VarName}_image_size = $($bytes.Length);
"@
}

Write-Host "=== VMM Shadow Mapper - Payload Header Generator ===" -ForegroundColor Cyan
Write-Host ""

# Generate DKOM block
Write-Host "Processing DKOM.sys..." -ForegroundColor Yellow
$dkomBlock = Convert-BinaryToCArray -FilePath $DkomPath -VarName "dkom"
if ($null -eq $dkomBlock) {
    Write-Error "Failed to process DKOM.sys"
    exit 1
}
Write-Host "  DKOM processed successfully" -ForegroundColor Green

# Generate RWbase block  
Write-Host "Processing RWbase.sys..." -ForegroundColor Yellow
$rwbaseBlock = Convert-BinaryToCArray -FilePath $RwbasePath -VarName "rwbase"
if ($null -eq $rwbaseBlock) {
    Write-Error "Failed to process RWbase.sys"
    exit 1
}
Write-Host "  RWbase processed successfully" -ForegroundColor Green

# Combine into header file
$headerContent = @"
#pragma once
// =============================================================================
// VMM Shadow Mapper - Embedded Payload Binaries
// Generated by generate_payload_header.ps1
// DO NOT EDIT MANUALLY - Regenerate from source .sys files
// =============================================================================

#include <cstddef>
#include <cstdint>

namespace payload {
$dkomBlock
$rwbaseBlock

} // namespace payload
"@

# Ensure output directory exists
$outputDir = Split-Path -Parent $OutputPath
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
}

# Write output file
$headerContent | Out-File -FilePath $OutputPath -Encoding UTF8
Write-Host ""
Write-Host "Generated: $OutputPath" -ForegroundColor Green

# Print verification info
Write-Host ""
Write-Host "=== Verification Info ===" -ForegroundColor Cyan

function Get-PEInfo {
    param([string]$FilePath, [string]$Name)
    
    $bytes = [System.IO.File]::ReadAllBytes($FilePath)
    
    # DOS Header check
    $dosSignature = [BitConverter]::ToUInt16($bytes, 0)
    if ($dosSignature -ne 0x5A4D) {
        Write-Host "  $Name : Invalid DOS signature" -ForegroundColor Red
        return
    }
    
    # Get NT Headers offset
    $ntOffset = [BitConverter]::ToInt32($bytes, 60)
    
    # NT Signature check
    $ntSignature = [BitConverter]::ToUInt32($bytes, $ntOffset)
    if ($ntSignature -ne 0x00004550) {
        Write-Host "  $Name : Invalid NT signature" -ForegroundColor Red
        return
    }
    
    # Optional Header offset (NT Header + 4 signature + 20 file header)
    $optionalOffset = $ntOffset + 4 + 20
    
    # Read key fields from Optional Header (64-bit PE)
    $magic = [BitConverter]::ToUInt16($bytes, $optionalOffset)
    $entryPoint = [BitConverter]::ToUInt32($bytes, $optionalOffset + 16)
    $imageBase = [BitConverter]::ToUInt64($bytes, $optionalOffset + 24)
    $sizeOfImage = [BitConverter]::ToUInt32($bytes, $optionalOffset + 56)
    
    Write-Host "  $Name :" -ForegroundColor Yellow
    Write-Host "    ImageBase:        0x$($imageBase.ToString('X16'))"
    Write-Host "    AddressOfEntry:   0x$($entryPoint.ToString('X8'))"
    Write-Host "    SizeOfImage:      0x$($sizeOfImage.ToString('X8')) ($sizeOfImage bytes)"
    Write-Host "    File Size:        $($bytes.Length) bytes"
}

Get-PEInfo -FilePath $DkomPath -Name "DKOM"
Get-PEInfo -FilePath $RwbasePath -Name "RWbase"

Write-Host ""
Write-Host "=== Complete ===" -ForegroundColor Green
